파이썬 개념학습<a href="#파이썬-개념학습" class="anchor-link">¶</a>
-------------------------------------------------------------------

### 변수<a href="#변수" class="anchor-link">¶</a>

-   변수 선언

In \[2\]:

    a = 'python'

-   변수의 예

In \[3\]:

    a = 'python'       # 문자열 변수
    b = 123            # 정수형 변수
    c = 1.2            # 실수형 변수
    c = ['a','b']      # 문자열 리스트
    d = {'name':'lee'} # 문자열 사전

### 주석문에 대한 설명<a href="#주석문에-대한-설명" class="anchor-link">¶</a>

In \[4\]:

    a = 100 # 주석문을 나타내는 방법

In \[5\]:

    '''
    다음과 같이 주석을 나타낼 수도 있음
    '''
    a

Out\[5\]:

    100

-   여러가지 변수 생성방법

In \[6\]:

    a,b = 'var1','var2'             
    # a에는 var1이라는 변수가 들어가며, b에는 var2라는 변수가 들어감
    c = ('tuple1', 'tuple2')   
    # c에는 tuple 자료 구조를 가진 (tuple1, tuple2) 라는 변수가 들어감 
    d = ['list1', 'list2']     
    # d에는 list 자료 구조를 가진 [list1, list2] 라는 변수가 들어감

    print(a)
    print(b)
    print(c)
    print(d)

    var1
    var2
    ('tuple1', 'tuple2')
    ['list1', 'list2']

-   데이터 변수 에러

In \[7\]:

    a = 10 # a변수에 10의 값을 할당
    g      # 하지만 g를 호출할 경우 g의 값은 아무 값도 할당하지 않았으므로 에러를 출력

    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-7-e466dddc6839> in <module>()
          1 a = 10 # a변수에 10의 값을 할당
    ----> 2 g

    NameError: name 'g' is not defined

-   데이터 변수 형태 확인

In \[8\]:

    a = 10    # a 변수에 10의 값을 할당
    b = 3.14  # b 변수에 3.14의 값을 할당
    c = True  # c 변수에 True라는 값을 할당

    print("a의 값은?", a)
    print("a의 데이터 변수 형태는?: ", type(a))  # a는 int형태의 값을 나타냄
    print("b의 값은?", b)
    print("b의 데이터 변수 형태는?: ", type(b))  # b는 float형태의 값을 나타냄
    print("c의 값은?", c)
    print("c의 데이터 변수 형태는?: ", type(c))  # c는 Boolean형태의 값을 나타냄

    a의 값은? 10
    a의 데이터 변수 형태는?:  <class 'int'>
    b의 값은? 3.14
    b의 데이터 변수 형태는?:  <class 'float'>
    c의 값은? True
    c의 데이터 변수 형태는?:  <class 'bool'>

### 자료형<a href="#자료형" class="anchor-link">¶</a>

-   기본 자료형

In \[9\]:

    a = 100    # 정수형 변수
    b = 3.14   # 소수형 변수

In \[10\]:

    print(a)
    print(bin(a))
    print(hex(a))
    print(oct(a))

    100
    0b1100100
    0x64
    0o144

-   논리형

In \[11\]:

    a=True

In \[12\]:

    type(a)

Out\[12\]:

    bool

In \[13\]:

    b = False

In \[14\]:

    type(b)

Out\[14\]:

    bool

-   비교 연산자를 이용해 논리형 데이터를 표현

In \[15\]:

    print(10 == 10) # 두 값이 같은 경우 True를 출력
    print(10 != 10) # 두 값이 같은 경우 False를 출력

    # 두 값 중 우측에 있는 값이 큰 경우 True를 출력 그렇지 않은 경우 False를 출력
    print(10 < 10)

    # 두 값 중 좌측에 있는 값이 큰 경우 True를 출력 그렇지 않은 경우 False를 출력
    print(10 > 10)

    # 두 값 중 우측에 있는 값이 크거나 같은 경우 True를 출력 그렇지 않을 경우 False를 출력
    print(10 <= 10)

    # 두 값 중 좌측에 있는 값이 크거나 같은 경우 True를 출력 그렇지 않을 경우 False를 출력
    print(10 >= 10)

    True
    False
    False
    False
    True
    True

-   문자열

In \[16\]:

    # sentence라는 변수에 두개의 문자열을 넣음
    sentence = '안녕하세요. '+"반갑습니다"  
    sentence

Out\[16\]:

    '안녕하세요. 반갑습니다'

In \[17\]:

    sentence.split() # sentence라는 변수를 띄어쓰기를 기준으로 split함수를 사용

Out\[17\]:

    ['안녕하세요.', '반갑습니다']

In \[18\]:

    # sentence라는 변수에 반갑습니다라는 단어를 찾기 위해 find함수를 사용
    sentence.find('반갑습니다') 

Out\[18\]:

    7

In \[19\]:

    # 만약 sentence라는 변수에 해당 문자열이 없을 시 -1 을 리턴함
    sentence.find('python')

Out\[19\]:

    -1

In \[20\]:

    # replace라는 변수에서 ',' 문자를 '!'문자로 변환하기 위해 replace 함수 사용
    sentence.replace('.', '!')  

Out\[20\]:

    '안녕하세요! 반갑습니다'

In \[24\]:

    # sentence라는 변수에서 '안녕'이라는 문자를 제거하기 위해 strip함수 사용
    sentence.strip('안녕')

Out\[24\]:

    '하세요. 반갑습니다'

### 자료구조<a href="#자료구조" class="anchor-link">¶</a>

#### (1) 리스트<a href="#(1)-리스트" class="anchor-link">¶</a>

In \[22\]:

    # 리스트의 형태
    data = [10, 20, 30, 40, 50, 60]  # data를 list형태로 생성
    print(data)                      # data의 값을 출력
    print(type(data))                # data에 저장된 형태를 나타냄

    [10, 20, 30, 40, 50, 60]
    <class 'list'>

In \[23\]:

    print(data[0])    # list형태의 data[0]번째를 출력
    print(data[4])    # list형태의 data[4]번째를 출력

    print(data)       # data에 저장된 값을 출력
    data[0] = data[4] # data[4]번째 값을 data[0]번째에도 같이 저장
    print(data)

    10
    50
    [10, 20, 30, 40, 50, 60]
    [50, 20, 30, 40, 50, 60]

#### (2) 리스트 인덱싱(indexing)<a href="#(2)-리스트-인덱싱(indexing)" class="anchor-link">¶</a>

In \[25\]:

    # data변수 안에 저장된 리스트 목록
    data = ["사과", "배", "포도", "딸기", "토마토", "메론"]
    print(data)

    # 인덱싱을 통해 리스트 내의 하나의 값을 표현하는 방법
    print("리스트 인덱싱을 통해 하나의 값을 표현: ", data[0])

    ['사과', '배', '포도', '딸기', '토마토', '메론']
    리스트 인덱싱을 통해 하나의 값을 표현:  사과

#### (3) 리스트 슬라이싱(slicing)<a href="#(3)-리스트-슬라이싱(slicing)" class="anchor-link">¶</a>

In \[26\]:

    data = ["사과","배","포도","딸기","토마토","메론"]

    #슬라이싱을 통해 리스트 내의 다수의 값을 나타낼 때 표현하는 방법
    print("리스트 슬라이싱을 통해 여러 값을 표현: ", data[2:4])

    리스트 슬라이싱을 통해 여러 값을 표현:  ['포도', '딸기']

-   리ㅅ트 인덱싱과 슬라이싱에서 발생하는 에러

In \[27\]:

    data = ["사과","배","포도","딸기","토마토","메론"]
    print(data)

    print(data[10])

    ['사과', '배', '포도', '딸기', '토마토', '메론']

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-27-41b6c6577df1> in <module>()
          2 print(data)
          3 
    ----> 4 print(data[10])

    IndexError: list index out of range

#### (4) 리스트 기초 연산<a href="#(4)-리스트-기초-연산" class="anchor-link">¶</a>

-   여러 개의 리스트를 하나의 리스트로 병합

In \[28\]:

    data_1 = [10, 20, 30, 40, 50] # 리스트형 data_1의 값
    data_2 = [5, 10, 15, 20, 25]  # 리스트형 data_2의 값

    # data_1과 data_2를 합쳤을 때 하나로 합쳐진 데이터 형태를 볼 수 있음
    data_1+data_2

Out\[28\]:

    [10, 20, 30, 40, 50, 5, 10, 15, 20, 25]

-   리스트 데이터를 추가 및 삭제

1\) 리스트의 append함수를 이용해 데이터를 추가하는 방법

In \[30\]:

    lists = [1, 100, 'python']
    print(lists)
    print(type(lists))
    print()

    # lists의 리스트에 py라는 값을 append함수를 이용해 데이터를 추가
    lists.append('py')
    print("py라는 값을 추가한 후의 lists: ", lists) # lists에 추가된 py라는 값을 확인

    [1, 100, 'python']
    <class 'list'>

    py라는 값을 추가한 후의 lists:  [1, 100, 'python', 'py']

2\) 리스트의 insert함수를 이용해 데이터를 추가하는 방법

In \[31\]:

    lists = [1, 100, 'python']
    print(lists)
    print(type(lists))
    print()

    # lists의 리스트에 py라는 값을 insert함수를 이용해 데이터를 추가
    lists.insert(1, '0.5')
    lists

    [1, 100, 'python']
    <class 'list'>

Out\[31\]:

    [1, '0.5', 100, 'python']

-   리스트 데이터를 추가 및 삭제

In \[32\]:

    print(lists)

    lists.remove('python')  # remove함수를 이용해 리스트의 'python' 값을 제거
    print(lists)

    [1, '0.5', 100, 'python']
    [1, '0.5', 100]

-   리스트 데이터의 최대, 최소값 구하기

In \[33\]:

    data_list = [10, 20, 30, 40, 50, 60, 70]

    # min함수를 이용해 리스트 데이터 중 최소값을 검색
    print("리스트 내에서 최소값을 찾을 때: ", min(data_list))

    # max함수를 이용해 리스트 데이터 중 최대값을 검색
    print("리스트 내에서 최대값을 찾을 때: ", max(data_list))

    리스트 내에서 최소값을 찾을 때:  10
    리스트 내에서 최대값을 찾을 때:  70

-   리스트 데이터 정렬하기

In \[34\]:

    data_list = [50, 20, 40, 30, 10, 60, 90]

    # sort함수를 이용해 리스트 데이터의 순서를 정렬
    data_list.sort()
    print(data_list)

    [10, 20, 30, 40, 50, 60, 90]

In \[ \]:

     

In \[12\]:

    tuples = (1, 100, '수학', 100)
    # 튜플은 기본적으로 ( )의 구조를 가짐

In \[13\]:

    print(tuples[0]) # 튜플 구조 내 0번째 자리를 확인
    print(tuples[2]) # 튜플 구조 내 2번째 자리를 확인

    1
    수학

In \[14\]:

    tuples.count(100) # 튜플 구조 안에 있는 100이라는 값의 개수를 출력

Out\[14\]:

    2

In \[15\]:

    tuple1 = (1, 2, 3, 'a', 'b', 'c') # 튜플 변수 저장
    tuple1[:3] #튜플 슬라이싱을 통해 3번째 이후의 값 출력

Out\[15\]:

    (1, 2, 3)

In \[16\]:

    tuple1 = (1, 2, 3)       # tuple1 변수에 1,2,3이라는 값 저장
    tuple2 = ('a', 'b', 'c') # tuple2 변수에 a,b,c라는 값 저장
    tuple1 + tuple2 # 두변수를 합하여 새로운 튜플구조를 만듦

Out\[16\]:

    (1, 2, 3, 'a', 'b', 'c')

In \[17\]:

    tuple1 = (1, 2, 3) # tuple1에 값 저장
    tuple1 * 3
    # 곱셈 연산 시 튜플구조를 3번 출력

Out\[17\]:

    (1, 2, 3, 1, 2, 3, 1, 2, 3)

In \[18\]:

    lists= [ 1, 100, '수학 ']
    # lists 라는 리스트 구조에 1과 100 그리고 '수학'이라는 값 저장
    print(lists[0])
    # lists의 0번째 자리수 출력
    print(lists[2])
    # lists의 2번째 자리수 출력

    1
    수학 

In \[19\]:

    lists.append('과학')
    # append 함수를 사용하여 '과학'이라는 값 추가
    lists

Out\[19\]:

    [1, 100, '수학 ', '과학']

In \[20\]:

    lists.insert(3,'100')
    # insert 함수를 사용하여 값을 추가
    # insert 함수는 append함수와 달리 위치를 입력 가능
    # insert(위치, 값)
    lists

Out\[20\]:

    [1, 100, '수학 ', '100', '과학']

In \[47\]:

    lists.remove('과학')
    # remove 함수를 사용하여 리스트 내 값 제거
    # lists 안에 있는 '과학'이라는 값을 제거
    lists

Out\[47\]:

    [1, 100, '수학 ', '100']

In \[ \]:

    # if문은 조건에 따라 수행되는 명령이 달라짐
    if 조건1 : 
    # 조건 1에 대한 수행문의 결과
        수행문 1
    else :
        수행문 2

In \[48\]:

    # 초기값으로 a라는 변수에 100의 값을 넣음
    a=100
    # a라는 변수가 100이라는 조건이 맞을 때
    # 일치라는 값을 출력하며, 아니면 불일치라는 값을 출력
    if a==100:
        print("일치")
    else:
        print("불일치")

    일치

In \[49\]:

    # 초기값으로 a라는 변수에 200의 값을 넣음
    a=200
    # a라는 변수가 200이라는 조건이 맞지 않으므로 불일치라는 값을 출력
    if a==100:
        print("일치")
    else:
        print("불일치")

    불일치

In \[ \]:

    while 조건문:
        수행문 1
        수행문 2

In \[51\]:

    # a라는 변수에 초기값 1을 설정
    a=1
    while a<=5:
    # while에 대한 조건문으로 a의 값이 5이하가 될때까지 반복
        print(a)
        a+=1
        # a라는 값을 1씩 더함

    1
    2
    3
    4
    5

In \[ \]:

    for 변수 in 리스트, 튜플, 문자열:
    # 리스트, 튜플, 문자열을 변수 값을 통해 받아옴
        명령문 1
        명령문 2
        # 명령문을 통해 실행

In \[21\]:

    num_list = [1,2,3,4,5]
    # num_list라는 리스트 구조의 변수에 1, 2, 3, 4, 5라는 값을 입력
    for num in num_list:
        # num_list의 값을 하나씩 num이라는 값에 집어 넣음
        print(num)
        # num이라는 값을 출력

    1
    2
    3
    4
    5

In \[ \]:

    def 함수명 (입력값):
        #함수를 사용하여 구조를 효율적으로 만듦
        명령문 1
        명령문 2
        return 출력값

In \[22\]:

    def f(x):
        # 함수 f(x)를 생성하고 x의 값을 입력 받음
        # 함수를 실행하였을 때 결과값으로 입력값 x에 10을 더한 결과가 나오게 함 
        return x + 10

    f(2)

Out\[22\]:

    12

In \[24\]:

    def f(x):
        # 하지만 변수가 없는 값을 넣었을 때는 에러가 발생함
        return y + 10
    f(2)

    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-24-8fb9bf29e5d3> in <module>()
          2     # 하지만 변수가 없는 값을 넣었을 때는 에러가 발생함
          3     return y + 10
    ----> 4 f(2)

    <ipython-input-24-8fb9bf29e5d3> in f(x)
          1 def f(x):
          2     # 하지만 변수가 없는 값을 넣었을 때는 에러가 발생함
    ----> 3     return y + 10
          4 f(2)

    NameError: name 'y' is not defined

In \[26\]:

    dictionary = {
                  'Name' : '홍길동',
                  'Email': 'gdHong@naver.com',
                  '주소' : '서울시 광진구'
                }
    type(dictionary)

Out\[26\]:

    dict

In \[27\]:

    dictionary.keys()
    # dictionary의 key의 값을 표현함

Out\[27\]:

    dict_keys(['Name', '주소', 'Email'])

In \[28\]:

    dictionary.values()
    # dictionary의 values의 값을 표현함

Out\[28\]:

    dict_values(['홍길동', '서울시 광진구', 'gdHong@naver.com'])

In \[64\]:

    dictionary.items()

Out\[64\]:

    dict_items([('Email', 'gdHong@naver.com'), ('주소', '서울시 광진구'), ('Name', '홍길동')])

In \[29\]:

    for item in dictionary.items():
        # for문을 사용하여 dictionary의 item의 값들을 출력
        # item함수는 dictionary구조 안에 있는 전체 값을 갖고 있는 함수
        print(item)

    ('Name', '홍길동')
    ('주소', '서울시 광진구')
    ('Email', 'gdHong@naver.com')

In \[66\]:

    set1 = set(['서울','대구','대전','부산','인천','강원'])
    # 집합(set)구조를 이용하여 객체를 생성
    set2 = set(['서울','부산','강원','충청','광주'])

In \[69\]:

    print(set1.union(set2))                      # set1, set2의 합집합 값 출력
    print(set1.intersection(set2))               # set1, set2의 교집합 값 출력
    print(set1.difference(set2))                 # set1, set2의 차집합 값 출력
    print(set1.symmetric_difference(set2))       # 둘 중 하나에만 속하는 값 출력

    {'서울', '대구', '대전', '강원', '부산', '인천', '충청', '광주'}
    {'서울', '부산', '강원'}
    {'대구', '대전', '인천'}
    {'대구', '대전', '충청', '인천', '광주'}

In \[30\]:

    nup = [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]  
    # nup이라는 변수에 실수 리스트를 생성
    flotV = [nup, nup, nup]                
    # flotV에 nup리스트를 3개 넣어 다차원 배열을 생성
    flotV                                  

Out\[30\]:

    [[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
     [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
     [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In \[31\]:

    flotV[0]
    # flotV는 다차원 배열을 갖음
    # flotV[N]을 통해 N차원 배열값을 추출 

Out\[31\]:

    [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In \[32\]:

    flotV[0]='Python'
    # flotV[0]의 차원에 위의 값 대신 'Python'이라는 값을 입력하여 값을 변환
    flotV

Out\[32\]:

    ['Python', [1.0, 10.4, 3.2, 5.1, 7.5, 2.7], [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In \[33\]:

    import numpy as np
    # numpy패키지를 np라는 명칭으로 축약시킴

    a = np.array([1, 2.5, 4.0, 5.5, 7.0])
    # np.array함수를 사용한 값을 a라는 변수에 넣음

    a[3:]
    # a의 3번째 자리수부터 출력

Out\[33\]:

    array([ 5.5,  7. ])

In \[34\]:

    a.sum()
    # np.array로 생성한 a라는 변수의 합을 출력

Out\[34\]:

    20.0

In \[36\]:

    a.std()
    # np.array로 생성한 a라는 변수의 표준편차를 출력

Out\[36\]:

    2.1213203435596424

In \[35\]:

    a.cumsum()
    # np.array로 생성한 a라는 변수의 누적 합을 출력

Out\[35\]:

    array([  1. ,   3.5,   7.5,  13. ,  20. ])

In \[37\]:

    print(a)          # 변수 a의 값을 출력
    print(a*2)        # a의 값에 2를 곱한 수를 출력
    print(a**2)       # a의 값에 2를 제곱한 수를 출력
    print(np.sqrt(a)) # a의 값에 루트를 적용한 수를 출력

    [ 1.   2.5  4.   5.5  7. ]
    [  2.   5.   8.  11.  14.]
    [  1.     6.25  16.    30.25  49.  ]
    [ 1.          1.58113883  2.          2.34520788  2.64575131]

In \[38\]:

    b = np.array([a, a**2])
    # 변수 a의 값을 b라는 변수에 변환하여 입력
    # a**2는 변수 a의 값을 제곱 함
    b

Out\[38\]:

    array([[  1.  ,   2.5 ,   4.  ,   5.5 ,   7.  ],
           [  1.  ,   6.25,  16.  ,  30.25,  49.  ]])

In \[39\]:

    b.sum(axis=0)

Out\[39\]:

    array([  2.  ,   8.75,  20.  ,  35.75,  56.  ])

In \[40\]:

    b.sum(axis=1)

Out\[40\]:

    array([  20. ,  102.5])

In \[44\]:

    np.array([[[0,0,0],[0,0,0]]]) 
    # 배열을 다음과 다르게 같이 표시 가능

Out\[44\]:

    array([[[0, 0, 0],
            [0, 0, 0]]])

In \[43\]:

    np.array([[[0,0,0],[0,0,0]]]) 
    # 위의 배열은 아래와 같이 표시 가능

    values = np.zeros((1,2,3), dtype='i')
    # np.zeros를 통해 값을 설정할 수 있으며 type 을 설정하여 배열을 사용 가능
    values

Out\[43\]:

    array([[[0, 0, 0],
            [0, 0, 0]]], dtype=int32)

In \[1\]:

    import numpy as np
    # numpy를 np로 축약하여 호출
    import pandas as pd
    # pandas를 pd로 축약하여 호출

    df = pd.DataFrame([100, 150, 200, 250], columns=['numbers'], index=['a','b','c','d'] )
    # DataFrame을 생성하며 columns이름은 numbers로 설정하고 index값은 a, b, c, d로 설정
    df

Out\[1\]:

|     | numbers |
|-----|---------|
| a   | 100     |
| b   | 150     |
| c   | 200     |
| d   | 250     |

In \[49\]:

    df.index
    # DataFrame의 index를 표시

Out\[49\]:

    Index(['a', 'b', 'c', 'd'], dtype='object')

In \[50\]:

    df.columns
    # DataFrame의 column을 표시

Out\[50\]:

    Index(['numbers'], dtype='object')

In \[51\]:

    df.ix['c']
    # DataFrame의 index값에서 c에 해당하는 값을 출력

Out\[51\]:

    numbers    200
    Name: c, dtype: int64

In \[115\]:

    df.sum() 
    # DataFrame값들을 전부 더함

Out\[115\]:

    numbers    700
    dtype: int64

In \[120\]:

    df.numbers**2
    # DataFrame의 numbers칼럼의 값을 제곱함

Out\[120\]:

    a    10000
    b    22500
    c    40000
    d    62500
    Name: numbers, dtype: int64

In \[113\]:

    df.ix[['a','d']]

Out\[113\]:

|     | numbers |
|-----|---------|
| a   | 100     |
| d   | 250     |

In \[114\]:

    df.ix[df.index[1:3]]

Out\[114\]:

|     | numbers |
|-----|---------|
| b   | 150     |
| c   | 200     |

In \[52\]:

    df['values'] = (10,50,40,50)
    # DataFrame에 values라는 칼럼을 추가하고 값을 넣음
    df

Out\[52\]:

|     | numbers | values |
|-----|---------|--------|
| a   | 100     | 10     |
| b   | 150     | 50     |
| c   | 200     | 40     |
| d   | 250     | 50     |

In \[53\]:

    df['values'] = (10,50,40) # DataFrame의 인덱스 수를 맞추지 않으면 에러 발생
    df

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-53-8c6bf4219d31> in <module>()
    ----> 1 df['values'] = (10,50,40) # DataFrame의 인덱스 수를 맞추지 않으면 에러 발생
          2 df

    C:\Users\Administrator\Anaconda2\envs\py34\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
       2297         else:
       2298             # set column
    -> 2299             self._set_item(key, value)
       2300 
       2301     def _setitem_slice(self, key, value):

    C:\Users\Administrator\Anaconda2\envs\py34\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
       2364 
       2365         self._ensure_valid_index(value)
    -> 2366         value = self._sanitize_column(key, value)
       2367         NDFrame._set_item(self, key, value)
       2368 

    C:\Users\Administrator\Anaconda2\envs\py34\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value)
       2522 
       2523             # turn me into an ndarray
    -> 2524             value = _sanitize_index(value, self.index, copy=False)
       2525             if not isinstance(value, (np.ndarray, Index)):
       2526                 if isinstance(value, list) and len(value) > 0:

    C:\Users\Administrator\Anaconda2\envs\py34\lib\site-packages\pandas\core\series.py in _sanitize_index(data, index, copy)
       2739 
       2740     if len(data) != len(index):
    -> 2741         raise ValueError('Length of values does not match length of '
       2742                          'index')
       2743 

    ValueError: Length of values does not match length of index

In \[131\]:

    del df['values'] # DataFrame의 values라는 칼럼을 삭제 
    df               

Out\[131\]:

|     | numbers |
|-----|---------|
| a   | 100     |
| b   | 150     |
| c   | 200     |
| d   | 250     |

In \[54\]:

    df['values'] = pd.DataFrame(['Fourth','Second','Third','First'], index=['d','b','c','a'])
    # 그림 72와 같이 DataFrame을 추가 시 다음과 같은 방법 사용 가능
    # index의 값에 일치하는 값을 넣음 
    df

Out\[54\]:

|     | numbers | values |
|-----|---------|--------|
| a   | 100     | First  |
| b   | 150     | Second |
| c   | 200     | Third  |
| d   | 250     | Fourth |

In \[1\]:

    import pandas as pd

    df_1=pd.DataFrame(['1','2','3'], columns=['A'])
    # A라는 Column에 1, 2, 3이라는 값을 넣음
    df_2=pd.DataFrame(['4','5','6','7'], columns=['B'])
    # B라는 Column에 4, 5, 6, 7이라는 값을 넣음
    df_1=df_1.join(df_2,how='outer')
    # 두개의 DataFrame을 outer join을 통해 합침
    df_1
    # 합친 DataFrame을 출력

Out\[1\]:

|     | A   | B   |
|-----|-----|-----|
| 0   | 1   | 4   |
| 1   | 2   | 5   |
| 2   | 3   | 6   |
| 3   | NaN | 7   |

In \[56\]:

    df=pd.DataFrame(np.random.rand(5,5),columns=['A','B','C','D','E'])
    # np.random.rand함수를 통해서 5x5의 행렬을 생성하고, column을 A, B, C, D, E라고 칭함
    df

Out\[56\]:

|     | A        | B        | C        | D        | E        |
|-----|----------|----------|----------|----------|----------|
| 0   | 0.552362 | 0.840545 | 0.512482 | 0.585907 | 0.505013 |
| 1   | 0.810637 | 0.677022 | 0.898684 | 0.620280 | 0.279422 |
| 2   | 0.327040 | 0.764590 | 0.728402 | 0.128712 | 0.519246 |
| 3   | 0.337440 | 0.346434 | 0.990106 | 0.523353 | 0.019222 |
| 4   | 0.169551 | 0.744478 | 0.609020 | 0.618002 | 0.266765 |

In \[58\]:

    df.max() # 각 칼럼별 최대값을 나타냄

Out\[58\]:

    A    0.810637
    B    0.840545
    C    0.990106
    D    0.620280
    E    0.519246
    dtype: float64

In \[57\]:

    df.min() # 각 칼럼별 최소값을 나타냄

Out\[57\]:

    A    0.169551
    B    0.346434
    C    0.512482
    D    0.128712
    E    0.019222
    dtype: float64

In \[59\]:

    df.mean() # 각 칼럼별 평균값을 나타냄

Out\[59\]:

    A    0.439406
    B    0.674614
    C    0.747739
    D    0.495251
    E    0.317934
    dtype: float64

In \[172\]:

    df.std() # 각 칼럼별 표준편차 값을 나타냄

Out\[172\]:

    A    0.269754
    B    0.231666
    C    0.331541
    D    0.324164
    E    0.342124
    dtype: float64

In \[60\]:

    df.cumsum() # 각 칼럼별 누적합 값을 나타냄, 그림 77과 비교

Out\[60\]:

|     | A        | B        | C        | D        | E        |
|-----|----------|----------|----------|----------|----------|
| 0   | 0.552362 | 0.840545 | 0.512482 | 0.585907 | 0.505013 |
| 1   | 1.363000 | 1.517567 | 1.411166 | 1.206187 | 0.784435 |
| 2   | 1.690040 | 2.282157 | 2.139568 | 1.334899 | 1.303681 |
| 3   | 2.027480 | 2.628591 | 3.129674 | 1.858252 | 1.322903 |
| 4   | 2.197031 | 3.373069 | 3.738693 | 2.476254 | 1.589668 |

In \[62\]:

    df.describe() # describe함수는 DataFrame의 요약값을 표현함

Out\[62\]:

|       | A        | B        | C        | D        | E        |
|-------|----------|----------|----------|----------|----------|
| count | 5.000000 | 5.000000 | 5.000000 | 5.000000 | 5.000000 |
| mean  | 0.439406 | 0.674614 | 0.747739 | 0.495251 | 0.317934 |
| std   | 0.248202 | 0.192495 | 0.197793 | 0.208602 | 0.205460 |
| min   | 0.169551 | 0.346434 | 0.512482 | 0.128712 | 0.019222 |
| 25%   | 0.327040 | 0.677022 | 0.609020 | 0.523353 | 0.266765 |
| 50%   | 0.337440 | 0.744478 | 0.728402 | 0.585907 | 0.279422 |
| 75%   | 0.552362 | 0.764590 | 0.898684 | 0.618002 | 0.505013 |
| max   | 0.810637 | 0.840545 | 0.990106 | 0.620280 | 0.519246 |

In \[64\]:

    df['division']=['X','Y','X','Y','Z'] 
    # Group by 하기 전 그룹별로 구별하기 위해 division이라는 칼럼을 생성
    df

Out\[64\]:

|     | A        | B        | C        | D        | E        | division |
|-----|----------|----------|----------|----------|----------|----------|
| 0   | 0.552362 | 0.840545 | 0.512482 | 0.585907 | 0.505013 | X        |
| 1   | 0.810637 | 0.677022 | 0.898684 | 0.620280 | 0.279422 | Y        |
| 2   | 0.327040 | 0.764590 | 0.728402 | 0.128712 | 0.519246 | X        |
| 3   | 0.337440 | 0.346434 | 0.990106 | 0.523353 | 0.019222 | Y        |
| 4   | 0.169551 | 0.744478 | 0.609020 | 0.618002 | 0.266765 | Z        |

In \[65\]:

    df.groupby(['division']).mean()
    # DataFrame Group by를 사용하여 칼럼 division의 값에 따라 평균값을 구함 

Out\[65\]:

A

B

C

D

E

division

X

0.439701

0.802567

0.620442

0.357309

0.512129

Y

0.574039

0.511728

0.944395

0.571817

0.149322

Z

0.169551

0.744478

0.609020

0.618002

0.266765

In \[180\]:

    num_list=[1,2,3,4,5]
    for num in num_list:
        print(num)

    1
    2
    3
    4
    5

In \[6\]:

In \[1\]:

In \[9\]:

     

    var1
    var2
    tuple1
    <class 'str'>
    tuple2
    list1
    list2

In \[11\]:

In \[14\]:

    print(a)        # 정수형 변수에 들어간 값 100 출력
    print(bin(a))   # 100이라는 값의 2진수 형태가 출력
    print(oct(a))   # 100이라는 값의 8진수 형태가 출력
    print(hex(a))   # 100이라는 값의 16진수 형태가 출력

    100
    0b1100100
    0o144
    0x64

In \[15\]:

    import pandas as pd
    import numpy as np

    pandas_series = pd.Series([3000,3200,2700], index=['2016-11-10','2016-11-11','2016-11-12'])
    # Series에 들어가는 값 생성
    print(type(pandas_series)) #Series의 타입을 확인

    <class 'pandas.core.series.Series'>

In \[16\]:

    pd.DataFrame(pandas_series) #Series를 DataFrame을 통해 출력

Out\[16\]:

|            | 0    |
|------------|------|
| 2016-11-10 | 3000 |
| 2016-11-11 | 3200 |
| 2016-11-12 | 2700 |

In \[18\]:

    pandas_series[1:] 
    # Series의 값을 위치를 통해 출력할 수 있다

Out\[18\]:

    2016-11-11    3200
    2016-11-12    2700
    dtype: int64